version: '3'
services:
  database:
    container_name: twitter-app-db
    image: "mongo:latest"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=devdatabase
      - MONGO_INITDB_ROOT_USERNAME=development
    volumes:
      - ./database/data:/data/db
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./api/dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - "database"
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=prod
  #     - DB_HOST=database