version: '3'
services:
  database:
    container_name: twitter-app-db
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=devdatabase
      - MYSQL_USER=development
      - MYSQL_DATABASE=twitter-app
    volumes:
      - ./database/data:/var/lib/mysql
  